name: Rodar Testes

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar uv
        uses: astral-sh/setup-uv@v5

      - name: Instalar dependências
        run: uv sync --frozen --no-install-project --all-extras

      - name: Rodar testes
        run: |
          uv run coverage erase
          uv run coverage run -m pytest src -vv --junitxml=./junit.xml
          uv run coverage xml -o coverage.xml
          uv run coverage report --show-missing

      - name: Rodar Migrations
        run: |
          uv run python src/manage.py migrate
          uv run python src/manage.py makemigrations --check --dry-run

      - name: Scanner do SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Envia cobertura para o Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: 2026.1-MeasureSoftGram-Service
          verbose: true
